import Head from 'next/head';
import HomePage from '../src/components/home/HomePage';
import styles from '../styles/Home.module.scss';

export default function Home(props) {
  const data = props.data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={data} />
    </div>
  );
}

export async function getServerSideProps() {
  const data = await import('/data/data.json');
  return {
    props: {
      data: data.events_categories,
    },
  };
}
